### ISSUE TITLE
Django 2.0+ Support

### ISSUE THREAD

**Issue by joshua-s** [kaleissin/django-verification#7] opened 2018-10-25 17:21 UTC
It would be great if this could support Django 2.0 and 2.1

**Comment by hmpf** [comment] 2018-10-26 09:15
Cool, does this mean there are **3** projects that maybe use this? :) This latest version was actually paid for, but I do need it to run on 2.x for a private project. The problem is: the paid dependent project is still on python 2.7 (It's the **last** project I need to touch on occasion that runs only on 2.7 I might add.) On the other hand, I don't *want* to keep supporting 2.7 so the next version will probably be purely python 3.x anyway.

**Comment by kaleissin** [comment] 2018-10-26 09:19
Cool, does this mean there are 3 projects that maybe use this? :) This latest version was actually paid for, but I do need it to run on 2.x for a private project. The problem is: the paid dependent project is still on python 2.7 (It's the last project I need to touch on occasion that runs only on 2.7 I might add.) On the other hand, I don't want to keep supporting 2.7 so the next version will probably be purely python 3.x anyway.

**Comment by joshua-s** [comment] 2018-10-26 13:44
I am looking to use it. It is actually possible to support all of those at once (and usually with minimal effort)!

**Comment by kaleissin** [comment] 2018-11-01 11:10
Tests pass for 2.0 and 2.1 locally now, and it still works on 1.8. If I push an alpha this Saturday (or just a branch) would yo have a chance to play with it? If it works out I'd make a 1.0 that officially doesn't support python 2.7/django 1.8 (trove classifiers etc.) and a 1.0.1 sometime later that attempts to remove the actual support.

Note to self,: The biggest/most annoying problem in porting to/supporting Django 2.x is that any migrations created earlier than Django 1.9 are incompatible with Django 2.x (1.8 does not record value of on_delete), so existing migrations need to be updated by hand.

**Comment by joshua-s** [comment] 2018-11-01 13:46
I'd love to check it out! Hoping to use this to generate 2FA and phone verification codes.

**Comment by kaleissin** [comment] 2018-11-03 18:59
The branch **django-2** is up. You should be able to install from that branch by

`pip install git+git://github.com/kaleissin/django-verification.git@django-2#egg=django-verification`

It'll say it's version 0.5.1 because I'm not bumping the version until I'm ready to distribute the new package on pypi, but you'll note in `verification.views` it's importing `reverse` in a try/except in order to work on both Django 1.8, 1.11, 2.0 and 2.1. (It is rather annoying how Django keeps moving things around.)

If it does what you need I'll package it ASAP, as version 1.0.0. If not, the branch will be here until I get around to upgrading a project that's currently on Django 1.11/python 3.5 which is currently perfectly happy depending on just 0.5.1.

**Comment by joshua-s** [comment] 2018-11-11 18:13
Thanks for that! There is an error which I believe is being caused by: https://github.com/kaleissin/django-verification/blob/master/setup.py#L24

**Comment by kaleissin** [comment] 2018-11-11 22:07
Done.

**Comment by joshua-s** [comment] 2018-11-18 21:47
Works pretty well for me! Thanks.

**Comment by kaleissin** [comment] 2018-11-20 22:52
I'll see if I can release a new version on Pypi on Sunday.

**Comment by joshua-s** [comment] 2018-11-20 22:56
Wonderful, thank you!

**Comment by kaleissin** [comment] 2018-11-25 21:45
0.5.2 and 1.0.0 up on Pypi, closing.

**Closed by kaleissin** 2018-11-25 21:45 UTC
